export enum TypeLookup {
  STATUS_USER = 1, // ESTATUS DEL USUARIO
  SERVICES_LIST = 2, // SERVICIOS (REUNIÓN, CHOFER, AUTO)
  STATUS_REQUEST = 3, // ESTATUS DE SOLICITUD (NUEVA, CANCELADA, EN REVISIÓN, ETC)
  LEVEL_MEETING = 4, // TIPO DE REUNIÓN (ADMINISTRATIVA O DIRECTIVA)
  INVENTORY_TYPE = 5, // TIPO DE INVENTARIO (Papelería, Botiquín, Limpieza, Cafetería)
  UNIT_TYPE = 6, // UNIDAD DE MEDIDA (Pieza, Caja, Paquete, Kilo, Galón, Garrafa, Par, Bolsa, Bote),
  STATUS_ROOM = 7, // (ACTIVA, BAJA, MANTENIMIENTO)
  REQUEST_TYPE_NOTIFICATIONS = 8 // (Sala, Automóvil, Conductor, Inventario)
}
