name: Deploy website on push PROD

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: |
          npm install
          npm run-script deploy-test

      - name: Copy files via SSH key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_HOST_TEST }}
          username: ${{ secrets.USERNAME_TEST }}
          key: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}
          source: "./dist"
          target: ${{ secrets.URL_FOLDER_PROD }}
          strip_components: 2
          rm: true
