name:  Deploy website on push MASTER!

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: dependencies-php-composer-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Create file ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Copy dotenv file
        run: |
          echo '${{ secrets.DOT_ENV_PROD }}' > .env
      - name: Generate key
        run: php artisan key:generate

      - name: Rsync files of Spatie's Google Calendar
        run: |
          touch GoogleCalendar.php
          echo -e "${{ secrets.GOOGLE_CALENDAR }}" > GoogleCalendar.php
          rsync -a GoogleCalendar.php ./vendor/spatie/laravel-google-calendar/src/GoogleCalendar.php
          rm GoogleCalendar.php
      - name: Rsync files of Spatie's Google Calendar Factory
        run: |
          touch GoogleCalendarFactory.php
          echo -e "${{ secrets.GOOGLE_CALENDAR_FACTORY }}" > GoogleCalendarFactory.php
          rsync -a GoogleCalendarFactory.php ./vendor/spatie/laravel-google-calendar/src/GoogleCalendarFactory.php
          rm GoogleCalendarFactory.php
      - name: Execute .sh to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_HOST_TEST }}
          username: ${{ secrets.USERNAME_TEST }}
          key: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}
          script: |
            rm -rf ${{ secrets.URL_FOLFER_PROD }}.git
            rm -rf ${{ secrets.URL_FOLFER_PROD }}app
            rm -rf ${{ secrets.URL_FOLFER_PROD }}bootstrap
            rm -rf ${{ secrets.URL_FOLFER_PROD }}config
            rm -rf ${{ secrets.URL_FOLFER_PROD }}database
            rm -rf ${{ secrets.URL_FOLFER_PROD }}public/css
            rm -rf ${{ secrets.URL_FOLFER_PROD }}public/js
            rm -rf ${{ secrets.URL_FOLFER_PROD }}resources
            rm -rf ${{ secrets.URL_FOLFER_PROD }}routes
            rm -rf ${{ secrets.URL_FOLFER_PROD }}tests
            rm -rf ${{ secrets.URL_FOLFER_PROD }}vendor
      - name: Copy files via SSH key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_HOST_TEST }}
          username: ${{secrets.USERNAME_TEST}}
          key: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}
          source: "./"
          target: ${{ secrets.URL_FOLDER_PROD }}
          overwrite: true
